### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by SergChr** [SergChr/react-blog#2]
## Tasks
- [ ] Create a Login page. Look at register page example.
### Subtasks
- [ ] Set route properly: should be `/login`.
- [ ] Similiar page styling with Login page.
